.pre-commit-config.yaml
.prospector.yml
README.md
custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/config_flow.py
custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/strings.json
custom_components/tesla_custom/translations/en.json
custom_components/tesla_custom/translations/no.json
info.md
tests/test_config_flow.py

This is all based off a submission from @omelhus in #26. Thanks to him for his submission.

Switch to refresh token

---

README.md
info.md

just a quick README update so that folks can more quickly get where they need to be.

Specify platform for authentication apps

---

README.md

Add link and small instructions to add the repository in HACS.

Add HACS Link

---

custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/sensor.py
poetry.lock
pyproject.toml

Hi,
This PR exposes the charge_current_request_max variable now available in teslajsonpy.  
Tested in HA and it presents the expected value. Ran black over changed files :)
Thanks

Expose charge_current_request_max attribute

---

README.md
info.md

I just had great success using https://github.com/DoctorMcKay/chromium-tesla-token-generator to generate my refresh token. It also made it trivial to verify that my token was not being transmitted to a third party, which as a paranoid delusional I loved. :)
Thank you for this awesome integration!

add chromium-tesla-token-generator to list

---

custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/switch.py
poetry.lock
pyproject.toml

Fix changes to function signature which broke the polling switch.
closes #142
closes #120 - Toggle polling switch to on

fix: fix polling switch enable api call

---

poetry.lock
pyproject.toml
tests/conftest.py

build: fix pytest fixture for later versions

---

custom_components/tesla_custom/sensor.py
hacs.json

https://developers.home-assistant.io/blog/2021/08/12/sensor_temperature_conversion/
closes #191

fix: address sensor breaking change

---

custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

fix: bump dependencies

---

custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

Fixes keyerror for vehicles lacking heated seats/steering wheels
closes #199

fix: bump teslajsonpy to 2.0.3

---

CHANGELOG.md
custom_components/tesla_custom/climate.py
custom_components/tesla_custom/helpers.py
custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

Entities that previously had to be manually enabled will automatically be enabled in HA.

feat: enable heated seat and steering wheel entities automatically

---

custom_components/tesla_custom/climate.py
custom_components/tesla_custom/helpers.py
custom_components/tesla_custom/select.py
custom_components/tesla_custom/switch.py

Fixes bug where the wrong seat heater or steering wheel heater was impacted for accounts with multiple vehicles.
Fixes #207

fix: check vin before adjusting climate devices (#208)

---

custom_components/tesla_custom/__init__.py

fix: use default if scan_interval settings missing

---

README.md
custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

Adds grid and home (load) power sensors for energy sites (solar systems).

Bump teslajsonpy to 2.4.1

---

custom_components/tesla_custom/manifest.json
poetry.lock

fix: bump teslajsonpy to fix solar naming (#249)

---

custom_components/tesla_custom/manifest.json

fix: fix grid status issue (#258)

---

custom_components/tesla_custom/device_tracker.py

Add LocationConverter when users use https://auth.tesla.cn to login.

fix #233 Car location offset

---

custom_components/tesla_custom/device_tracker.py

closes #233 
Co-authored-by: Emniroll <emniroll@outlook.com>

fix: fix Chinese location offset (#263)

---

custom_components/tesla_custom/translations/da.json

Updated Danish Translation

---

custom_components/tesla_custom/cover.py

Added async_close_cover method to the TeslaCarFrunk class

fix: issue #307

---

custom_components/tesla_custom/cover.py

fix: add missing close_cover for frunks

---

custom_components/tesla_custom/binary_sensor.py
tests/mock_data/car.py
tests/test_binary_sensor.py

closes https://github.com/alandtse/tesla/issues/310

feat: add doors binary sensor

---

custom_components/tesla_custom/button.py
custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml
tests/test_button.py

feat: add remote start button (#385)

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

fix: don't round when tpms is unavailable (#398)

---

README.md
custom_components/tesla_custom/select.py
tests/test_select.py

closes https://github.com/alandtse/tesla/issues/392

fix: check climate on when turn seat heater on

---

custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/switch.py
poetry.lock
pyproject.toml
tests/mock_data/car.py
tests/test_switch.py

Will require https://github.com/zabuldon/teslajsonpy/pull/374
I'll bump teslajsonpy and poetry lock once ready.
closes https://github.com/alandtse/tesla/issues/355

feat: valet mode switch

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

fix: use old pressure consts for ha < 2022.11 (#418)

---

custom_components/tesla_custom/device_tracker.py
custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/sensor.py
poetry.lock
pyproject.toml
tests/mock_data/car.py
tests/test_device_tracker.py
tests/test_sensor.py

2022-12-11

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

closes https://github.com/alandtse/tesla/issues/412

feat: Est battery range attributes

---

custom_components/tesla_custom/binary_sensor.py
tests/test_binary_sensor.py

closes https://github.com/alandtse/tesla/issues/221

feat: User present and User ID

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

closes https://github.com/alandtse/tesla/issues/450

fix: handle battery range attributes NoneType

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

fix: handle battery range attributes NoneType (#453)

---

custom_components/tesla_custom/manifest.json

https://github.com/home-assistant/architecture/discussions/715

feat: Add loggers to manifest for dynamic debug logging

---

custom_components/tesla_custom/binary_sensor.py
tests/test_binary_sensor.py

Includes fix for scheduled departure binary state when a charger is plugged in. Discussion [here](https://github.com/alandtse/tesla/discussions/408#discussioncomment-4487304)

feat: sch depart and charge timestamp attributes

---

CHANGELOG.md
README.md

Updated the wording for where to loate the Integrations page in HASS

Updated wording

---

.github/workflows/semantic_release.yml
custom_components/tesla_custom/sensor.py
tests/test_sensor.py

2023-02-21

---

custom_components/tesla_custom/teslamate.py
custom_components/tesla_custom/util.py

Added more values to be updates from MQTT.
Added a little extra logging

feat: More updates to TeslaMate

---

custom_components/tesla_custom/teslamate.py
custom_components/tesla_custom/text.py

There was a bug where the initial code was not able to subscribe to multiple cars.
This update adds more logging for debugging in the future, and fixes the MQTT issues.
It also has better handling of the file storage for the TeslaMate IDs in the text box.
Fixes
https://github.com/alandtse/tesla/issues/581

fix: multiple cars for TeslaMate

---

custom_components/tesla_custom/climate.py
custom_components/tesla_custom/cover.py
custom_components/tesla_custom/lock.py
custom_components/tesla_custom/number.py
custom_components/tesla_custom/select.py
custom_components/tesla_custom/switch.py
custom_components/tesla_custom/text.py

fix: use async_write vs async_update

---

custom_components/tesla_custom/select.py
custom_components/tesla_custom/switch.py
tests/test_select.py
tests/test_switch.py

This should hopefully fix https://github.com/alandtse/tesla/issues/633 but as i don't have a older model S, I can't test explicitly.

fix: variable heated steering for older cars

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

feat: minutes-to-arrival-attribute

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

fix: check if arrival time attribute is available

---

custom_components/tesla_custom/manifest.json

changelog: https://github.com/zabuldon/teslajsonpy/compare/v3.9.0...v3.9.2
fixes slow startup, fixes energy sites sometimes not coming available, improves performance

fix: bump teslajsonpy to 3.9.2

---

custom_components/tesla_custom/teslamate.py

Avoid excessive logging while driving

fix: Change MQTT-update logging to DEBUG

---

custom_components/tesla_custom/const.py
custom_components/tesla_custom/manifest.json
pyproject.toml

chore: update version numbers

---

CHANGELOG.md
custom_components/tesla_custom/const.py
custom_components/tesla_custom/manifest.json
pyproject.toml

This is a fake commit to sync tags, commits, and versions.

[skip ci] 3.15.3

---

custom_components/tesla_custom/teslamate.py

fix: Pass correct variable to cast_bool

---

custom_components/tesla_custom/teslamate.py

fix: fix processing of teslamate trunk opening (#701)

---

custom_components/tesla_custom/services.py

Fixes https://github.com/alandtse/tesla/issues/737

feat: Update services.py to return responses

---

CONTRIBUTING.md

This pull request addresses and corrects grammatical and spelling errors throughout the codebase to improve code readability.
The changes include fixing typos, punctuation, and ensuring proper sentence structure without introducing functional modifications.
These updates are intended to enhance the quality of documentation and code comments.
The focus is on making the codebase more polished and user-friendly by eliminating language-related issues.

docs(grammatical): correct typos and improve grammar

---

custom_components/tesla_custom/teslamate.py

The previous code would always update the charging state when receiving a new car state. This could sometimes cause the charging state to be set to "Disconnected" even when the car was physically connected. Avoid this by only changing the charging state if the new received car state is "charging". Otherwise don't modify the charging state of the car. Hopefully this should lead to consistent behavior.
Fixes #761

fix: modify charging state only when car is 'charging'

---

custom_components/tesla_custom/teslamate.py

fix: modify charging state only when car is 'charging' (#764)

---

.pre-commit-config.yaml
custom_components/tesla_custom/sensor.py

Refer Discusssion https://github.com/alandtse/tesla/discussions/859
thanks.

fix: return float for charger power output

---

custom_components/tesla_custom/sensor.py

fix: check sensor value is valid before casting

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/config_flow.py

fix: key error for CONF_API_PROXY_CERT

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/config_flow.py

fix: key error for CONF_API_PROXY_CERT (#890)

---

custom_components/tesla_custom/config_flow.py

fix: UnboundLocalError when supervised without addon

---

.github/workflows/pull.yml
custom_components/tesla_custom/select.py

Fixes the KeyError mentioned in [996](https://github.com/alandtse/tesla/issues/996). Not entirely sure if it'll fix the battery sensor issue.

fix: fix keyerror for seatmap

---

custom_components/tesla_custom/select.py

fix: fix keyerror for seatmap (#997)

---

custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml
scripts/setup

Bump teslajsonpy to 3.12.2 which includes fix for API service

fix: Bump teslajsonpy to 3.12.3
