alandtse/tesla

README.md
custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/config_flow.py
info.md
tests/test_config_flow.py

fix: use http.httpstatus constant

---

README.md

I had a heck of a time running down how to turn on my Tesla's climate via a scene; looks like [I'm not alone](https://community.home-assistant.io/t/help-with-climate-automation-tesla/39644). Here's the scene that finally worked for me:
```yaml
- name: I'm Getting Ready to Leave
icon: "mdi:car"
entities:
climate.tesla_model_y_hvac_climate_system:
state: heat_cool
```
Based on the docs I was expecting to need to set `state` to `on` and `hvac_mode` to `heat_cool`.

Add a note in the docs about how to turn on climate via a scene

---

custom_components/tesla_custom/device_tracker.py

Forced updates are only needed if we are [not polling](https://github.com/home-assistant/core/blob/dev/homeassistant/components/device_tracker/config_entry.py#L204). Since the coordinator
is effectively doing the polling instead of Home Assistant internals doing it
via should_poll set to True, we need to set the property manually to avoid
writing a state update every time the coordinator callback happens to avoid
a state changed event when nothing has really changed.

Disable forced updates for device trackers

---

custom_components/tesla_custom/device_tracker.py

Forced updates are only needed if we are not polling. Since the coordinator
is effectively doing the polling instead of Home Assistant internals doing it
via should_poll set to True, we need to set the property manually to avoid
writing a state update every time the coordinator callback happens to avoid
a state changed event when nothing has really changed.

fix: disable forced updated for device trackers (#158)

---

custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

Removes deprecated get_bearer_step
closes #165

fix: bump teslajsonpy to 1.9.0

---

README.md
custom_components/tesla_custom/button.py
custom_components/tesla_custom/const.py

This PR adds a 'trigger homelink" button to the Tesla integration, which is disabled by default.
It works by taking the current location of the vehicle to feed into the required lat/lon params for the API call, which would normally be the user phone's location when called by the official Tesla app. For users this means it's possible to remotely open/close the homelink device (please always monitor surroundings for safety).
The button will be disabled by default in HA, and would need to manually be enabled by the the user if they wish to utilize it.
If enabled, it would still show as unavailable in these cases:
- if the vehicle does not have the homelink option purchased/installed.
- if the vehicle has no homelink devices programmed.
- if the vehicle is unreachable (as is normal behavior …

feat: add trigger homelink button (disabled by default)

---

CHANGELOG.md
README.md
custom_components/tesla_custom/climate.py
custom_components/tesla_custom/helpers.py
custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

This PR will enable heated seats and heated steering wheel entities based on the capability of the vehicle.
This allows those entities initially to be created as disabled, but first time climate data is received those that are available are then enabled.
Enabling is only checked once per startup once data has been received. Once an entity is enabled is will stay enabled.
An entity that was disabled by the user will not be re-enabled again.
If approved then I plan to update teslajsonpy to make all heated seats and the heated steering wheel switch as disabled by default. 
Note, that anyone who already has those entities now will not see any change since they are then already enabled. This will only be seen when newly adding the component.

Enable heated seat and steering wheel based on capability of vehicle

---

custom_components/tesla_custom/climate.py
custom_components/tesla_custom/helpers.py
custom_components/tesla_custom/select.py
custom_components/tesla_custom/switch.py

When we are updating other devices, we need to ensure we do so on the same device on the same car.
Fixes https://github.com/alandtse/tesla/issues/207

Match Devices to the same VIN.

---

custom_components/tesla_custom/tesla_device.py

The call to async_get_registry in tesla_device.py gives a deprecation warning in 2022.6b0, this PR changes the async call to async_get. 
This should work for 2022.5.x too but haven't been able to test that.

async_get_registry is deprecated in 2022.6, use async_get instead

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/tesla_device.py

Enables the Delete device button on the devices page
I had duplicate devices since at some point the identifiers had changed

Add support for async_remove_config_entry_device

---

custom_components/tesla_custom/manifest.json
poetry.lock

Bump teslajsonpy to 2.4.3 which includes:
- Fix for solar system naming
- Fix for only adding load and grid sensors for energy sites with a load meter
- Better handling for grid status "Unknown" issue with some energy sites

Bump teslajsonpy to 2.4.2 to fix solar naming

---

custom_components/tesla_custom/manifest.json

Fixes issue where some energy sites only report `grid_status` when it's `Unknown`.
Fixes #257.
Requires [this teslajsonpy pull request](https://github.com/zabuldon/teslajsonpy/pull/346) to be merged and published first.

Bump teslajsonpy to 2.4.4

---

README.md

Removes some duplicate info from the README that was added while resolving conflicts from the re-write.

Remove duplicate info from README

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

- Specify device class for sensors to allow users to specify the unit of measurement for each entity.
- Reverts a [previous PR](https://github.com/alandtse/tesla/pull/288) but this still fixes #284. Specifically, if a UK user has their Home Assistant Unit System set to metric, they can still set the units for the odometer to miles (one example).

fix: set sensor device class

---

custom_components/tesla_custom/cover.py

Fixes #298
Temporarily using the `powered_lift_gate` key for the trunk to determine whether or not we add the close feature to the frunk entity. I rather default to having it there for folks that have it then not.

fix: add open feature for frunk

---

README.md
custom_components/tesla_custom/lock.py
tests/test_lock.py

https://github.com/alandtse/tesla/issues/323
Feature working in the dev container. 
There is no option to close the latch with Tesla's API. The car itself handles that. I could not find a way to hid the "lock" feature so I'm having it throw a message in the logs that it cannot be locked. I'm not sure what is best practice in that situation.

feat: Add charge port latch lock, #323

---

custom_components/tesla_custom/binary_sensor.py
tests/test_binary_sensor.py

For #360 
This adds a binary sensor which is `on` if the car is asleep, allowing automations, dashboards, etc to reflect if the car is asleep vs unreachable.
This also adds a `state` attribute to `binary_sensor.<car>_online`, allowing for a bit more insight into the variations of the car's "online-ness"

feat: add binary_sensor.<car>_asleep

---

custom_components/tesla_custom/binary_sensor.py

I forgot to add this to #361, this sets the icon to be more relevant to the sensor, rather than using the generic circle icon.

fix: update car-asleep binary sensor icon

---

custom_components/tesla_custom/manifest.json
custom_components/tesla_custom/sensor.py
poetry.lock
pyproject.toml
tests/mock_data/car.py
tests/test_sensor.py

For #359 
This updates the battery sensor for vehicles to use the `usable_battery_level` value so that it matches the Tesla app and in-car display in all weather conditions.
Additionally a `raw_soc` attribute is added to the battery sensor to provide insight into the battery's SOC, which does not change with temperature. This allows for users to detect reduced range due to cold (such as the snowflake icon in the app) if they wish to do so.
Lastly this PR fixes a bug in that the battery icon did not reflect Charging status due to a typo that I happened to notice while doing the above.

fix: vehicles use usable_battery_level to match app

---

poetry.lock
tests/test_sensor.py

Updating homeassistant brought about failures in existing tests due to hass automatically converting units in sensors from miles to km (and speed equivalents).
There doesn't seem to be a way to globally disable unit conversion for tests, so this PR fixes failing tests by converting the mock values if necessary. This feels like a hack, so I'm open to suggestions. I alternatively tried setting `hass.config.units` to imperial, but that breaks the temperature tests since it converts the mock Celsius temps into Fahrenheit, so a conversion of the mock values would be needed regardless.

fix: Update tests for hass built-in unit conversions in 2022.11

---

custom_components/tesla_custom/update.py
tests/mock_data/car.py
tests/test_update.py

I had a software update last night, so I seized the opportunity to collect api responses of the different states, and provide some improvements to the update component.
This makes a few improvements:
- Ensures the install button isn't available until the update is downloaded (it is hidden when waiting on wifi or still downloading)
- Ensures the install button is available when the update is scheduled, in case the user wants to install immediately.
- Shows the status (Downloading, Waiting on Wi-Fi, etc) in the latest version string to indicate to the user why the install button is not yet available, or to show if it's already scheduled.
- No longer shows as "Installing" when it's scheduled, #356 
Some examples

feat: show software update statuses in version info

---

custom_components/tesla_custom/sensor.py

Looks like HA [stores all times in UTC](https://www.home-assistant.io/blog/2015/05/09/utc-time-zone-awareness/) then converts that value to the user's timezone. So using utcnow() instead of now() fixes the timezone issue with this sensor. 
closes https://github.com/alandtse/tesla/issues/374

fix: time charge complete timezone bug

---

custom_components/tesla_custom/sensor.py

Looks like HA stores all times in UTC then converts that value to the user's timezone. So using utcnow() instead of now() fixes the timezone issue with this sensor.
closes #374

fix: use utc time zone for charge complete sensor

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

fix: don't try to round when tpms is unavailable

---

custom_components/tesla_custom/cover.py

Updated device class for car windows to fix counterintuitive arrows. I also changed the entity icon to better reflect a car window. I will be following this up with a PR to HA to request a device class more suited for car windows.

fix: #394 Fixed counterintuitive arrows for window cover

---

custom_components/tesla_custom/sensor.py

Fixes #295 and #413 
Based on the information [here](https://developers.home-assistant.io/docs/core/entity/sensor/#entities-representing-a-total-amount), I realized that the logic to set the energy added to 0 when not charging was breaking energy calculations.
The actual energy added value is reset by tesla on it's own, so when we manually set 0, and then revert back to the tesla's value if charging starts again for the same charge session, it will cause the energy dashboard to incorrectly sum the deltas.
It appears that TOTAL_INCREASING is the right state class to use, as we don't expect the value to decrease substantially (a 10% allowance is built in). So if we just rely on the car's own charging state to reset appropriately, the energy dashboard should reflect usage correctly.
What …

fix: always show charge energy for current and last session

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

Fixes the pressure unit imports to be compatible with home assistant versions before 2022.11. this breakage was introduced in #391 
Fixes #417 
The new unit enums were only released in 2022.11, and many users have not upgraded to this yet
https://developers.home-assistant.io/blog/2022/10/26/new-unit-enumerators/
There does not yet appear to be an announcement that the old units are being removed, so we can continue using them for now.

fix: use old pressure unit consts for ha < 2022.11

---

custom_components/tesla_custom/select.py
tests/test_select.py

Will need to make sure this fully addresses https://github.com/alandtse/tesla/issues/433

fix: seat map different for auto climate command vs remote seat command

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

I discovered while testing on HA dev branch that there is a new check to ensure only numeric sensors are reporting a state class (core PR 83344)
With this new check, it logs an error message that some of our sensors are non-numeric, but have a state class
```
Traceback (most recent call last):
[...]
File "/usr/local/python/lib/python3.10/site-packages/homeassistant/components/sensor/__init__.py", line 797, in state
raise ValueError(
ValueError: Sensor sensor.mystique_time_charge_complete has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp
```
This PR fixes this error, and also fixes the history graphs for these sensors to not try to map the timestamp to a line chart (which results in unreadable values on the chart as it's …

fix: remove state class from timestamp sensors

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

Saves the time when the value changes, subtracts the time that has passed since the last update. 
Without this the value grows by 1 minute for every minute since an api update. Then, on api call, the time jumps back down to the proper time.

fix: Charge time remaining, account for time passing between updates

---

.pre-commit-config.yaml
custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml

A fix to the set charge current function was made in the upstream library, and so a bump is required to fix https://github.com/alandtse/tesla/issues/479

fix: Bump teslajsonpy to fix charge current

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

Passing minutes_to_full_charge as an attribute of time_charge_complete sensor.
Still investigating the behavior seen in https://github.com/alandtse/tesla/issues/497

feat: add min_to_full_charge attribute

---

custom_components/tesla_custom/base.py

slugify is a relatively expensive operation because it has to do unicode work. 
Ideally we could use `self._attr_unique_id` in `__init__` but `self.type` is set after the parent's `__init__` is called.

fix: memorize unique id

---

custom_components/tesla_custom/__init__.py

https://docs.python.org/3/library/asyncio-task.html#creating-tasks
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:

fix: use async_create_background_task to close the httpx client

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/config_flow.py
custom_components/tesla_custom/util.py

Creating an ssl context does I/O in the event loop because it reads the ssl certificates from disk.
This is compounded by creating SSLContext leaking memory on some versions of openssl
Try to use the default one if its available to avoid this.

fix: use Home Assistant ssl context to avoid I/O

---

custom_components/tesla_custom/base.py
custom_components/tesla_custom/sensor.py

Add a new Cara Data update time sensor.
This is so you can easily use the sensor in "wait for" automations after forcing a data update via the force update button.

feat: Add Car Data Update Time Sensor

---

custom_components/tesla_custom/sensor.py
hacs.json
pyproject.toml

Add a car Shift state ENUM sensor, so you can detect what gear the car is in specifically.
This is different to the Parking Break binary sensor, as you get the explicit gear.

feat: Add Shift State Sensor

---

custom_components/tesla_custom/sensor.py
tests/test_sensor.py

Added absolute value around the seconds comparison to allow for a state change when the charge complete time and the arrival time move earlier than before. 
closes https://github.com/alandtse/tesla/issues/565

fix: Update state with earlier charge complete and arrival times

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/teslamate.py

This update batches updates from TeslaMate so less calls are made to `async_update_listeners`.
The main reason for this is the destination tracker updates. currently, as Lat and Long are different updates, the location of the Tesla can zig/zag as it moves along a line.
This normalizes that data.
calls to `async_update_listeners` will happen no more than once a second, but no less then once ever 0.1 seconds.
I won't hide the fact that ChatGPT helped me write this code :)

fix: Debounce teslamate updates

---

custom_components/tesla_custom/__init__.py

Only create the `update_vehicles` coordinator if there are cars to be polled
Add a listener to the `update_vehicles` to ensure we continue to poll the `vehicles` endpoint since the lack of listeners previously meant the endpoint was not being polled.

fix: ensure update_vehicles coordinator always polls

---

custom_components/tesla_custom/base.py
custom_components/tesla_custom/binary_sensor.py
custom_components/tesla_custom/button.py
custom_components/tesla_custom/climate.py
custom_components/tesla_custom/cover.py
custom_components/tesla_custom/device_tracker.py
custom_components/tesla_custom/lock.py
custom_components/tesla_custom/number.py
custom_components/tesla_custom/select.py
custom_components/tesla_custom/sensor.py
custom_components/tesla_custom/switch.py
custom_components/tesla_custom/text.py
custom_components/tesla_custom/update.py

- Reduce some lookups when writing state
- Remove `__init__` delegations where the attributes are static

fix: small cleanups to entity construction

---

custom_components/tesla_custom/base.py
custom_components/tesla_custom/binary_sensor.py
custom_components/tesla_custom/button.py
custom_components/tesla_custom/climate.py
custom_components/tesla_custom/cover.py
custom_components/tesla_custom/device_tracker.py
custom_components/tesla_custom/lock.py
custom_components/tesla_custom/number.py
custom_components/tesla_custom/select.py
custom_components/tesla_custom/sensor.py
custom_components/tesla_custom/switch.py
custom_components/tesla_custom/teslamate.py
custom_components/tesla_custom/text.py
custom_components/tesla_custom/update.py

followup to #670
I was trying to speed up the setup a bit as well, but the real cause of the slow setup when the car is asleep is https://github.com/zabuldon/teslajsonpy/pull/416

fix: reduce entity creation code

---

custom_components/tesla_custom/teslamate.py

This changes the log level for a message recorded when MQTT is not enabled from WARNING to INFO.  I believe this is the correct way to fix https://github.com/alandtse/tesla/issues/601 considering that the condition is expected when `Sync Data from TeslaMate via MQTT` is not enabled in the integration configuration.

fix: Remove TeslaMate MQTT warning at every HA startup

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/services.yaml
custom_components/tesla_custom/strings.json
hacs.json

BREAKING CHANGE: Home Assistant Core 2023.6.0 or later is now required
fixes https://github.com/alandtse/tesla/actions/runs/5677167144/job/15385034940
Note: we can't remove from services.yaml since old version still need it

fix: add missing CONFIG_SCHEMA and service translations

---

custom_components/tesla_custom/teslamate.py

Fixes #689
- parse boolean strings for is_climate_on, locked, sentry_mode
- add sync for plugged_in
- add sync for charge_port_door_open
- add sync for trunk_open
- add sync for frunk_open
- add sync for is_user_present
- add sync for is_preconditioning

fix: Improve a couple of things in MQTT sync from Teslamate

---

custom_components/tesla_custom/teslamate.py

Re-use cast-method from odometer since they both are reported in km from Teslamate and need to be converted to miles for teslajsonpy to be happy.

feat: Add MQTT sync from Teslamate for battery_range

---

custom_components/tesla_custom/teslamate.py

Add sync for `charge_current_request` and `charge_current_request_max` from Teslamate.

feat: Add charge_current_request properties from MQTT

---

README.md

Fixed Spelling and Grammatical Errors in ReadMe.md
"If no HACS" to "If you do not have HACS,"
"esentially"  to "essentially."
"requies" to "requires."

docs: fix errors in ReadMe.md

---

tests/mock_data/energysite.py
tests/test_button.py
tests/test_climate.py
tests/test_cover.py
tests/test_lock.py
tests/test_number.py
tests/test_select.py
tests/test_switch.py
tests/test_update.py

Fix the tests!
Most tests just had a broken `hass.services.async_call`.
`hass.services.async_call` no longer returns a boolean, as documented here:
https://developers.home-assistant.io/blog/2023/06/14/service-calls/
Fix: just don't look at the return value anymore.
However, some tests fail due to mismatch in mock data and teslajsonpy and/or extraction code in `sensor.py`.
I have fixed them by modifying the mock data.
Not sure if that is the correct approach. Are there recent examples of SolarPowerwallSite responses?

test: Fix tests

---

custom_components/tesla_custom/number.py
custom_components/tesla_custom/teslamate.py

Since Teslamate doesn't map directly to TeslaCar from teslajsonpy,
we need to have special handling of both 'plugged_in' and 'state'
when they come from Teslamate. When we receive a new 'plugged_in'-value,
we check the `car.state` to determine the new 'charging_state'
in teslajsonpy, and similarly we need to check the `car.charging_state`
when Teslamate sends a new car-state.
Also refactor the MQTT-code slightly to avoid multiple implementations
of the code that updates the TeslaCar-object.
Fixes #712

feat: Sync car state from Teslamate MQTT

---

custom_components/tesla_custom/teslamate.py

Apparently, the `battery_range` attribute of teslajsonpy maps to the `rated_battery_range_km` property from Teslamate. Fix this, and also export the other ranges from Teslamate correctly this time.
Should fix #740

fix: fix range attributes from Teslamate

---

custom_components/tesla_custom/teslamate.py

The last commit unfortunately removed the MQTT-sync for `usable_battery_level` by mistake. Re-add the line to sync `usable_battery_level` from Teslamate

fix: Re-add usable_battery_level from mqtt

---

custom_components/tesla_custom/manifest.json
poetry.lock
pyproject.toml
scripts/setup

In order to fix issue #756, we need to have https://github.com/zabuldon/teslajsonpy/pull/437 merged. This was implemented in teslajsonpy version 3.9.8. As mentioned by [dagstuan](https://github.com/dagstuan) in #770

fix: Bump teslajsonpy to 3.9.8

---

.github/ISSUE_TEMPLATE/issue_car.yml
.github/ISSUE_TEMPLATE/issue_form.yml

Here's an initial attempt at creating an issue form to get information from users using the current new issue template as the basis.
I am in two minds if this should be a bug form rather than a general issue one, given the questions asked/input required?

chore: add issue form for car

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/base.py

assumed_state on the entities was calculated for each entity. We can calculate it once per update instead.

fix: calculate assumed state only once

---

custom_components/tesla_custom/manifest.json

This option is new for 2024.3. Previously all integrations had to be imported in the event loop which would block the loop while it happened.
This option is safe to add for pre 2024.3 as it will do nothing.
This could be considered `pref` but not blocking the event loop is might always considered a fix

fix: avoid blocking the event loop during import

---

.devcontainer.json
.github/workflows/pull.yml
.github/workflows/push.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
scripts/setup

This just updates the dev environment to make a more accurate real world test.  I haven't tested this in real life yet, I only ran it for a few minutes in the dev container and verified that everything comes up fine.
Closes #876.

build: Bump dev to Home Assistant 2023 and python 3.12

---

custom_components/tesla_custom/config_flow.py
tests/test_config_flow.py

Client ID should be `ownerapi` for compatibility with old style.
Fixes #889

fix: set default client_id ownerapi

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_powerwall.yml

Quite often we're seeing issues created without filling in the required information. With this the template should make this easier for people to understand what we need and how to get it from their Home Assistance instance.
This creates a new Powerwall issue template and also disables the blank issue creation

chore: Ensure issues are created using templates

---

README.md

Update the description of how to determine if you need the Fleet Proxy (the error messages seem to have changed) and reinforce that this is most vehicles and likely required for anyone going through a fresh install.

docs: Update Fleet Proxy info in README.md  

---

.github/ISSUE_TEMPLATE/issue_car.yml

Try and reduce API readonly issues being raised with non-fleet api by highlighting the information in the `readme.md`

chore: Add Fleet API warning

---

custom_components/tesla_custom/__init__.py

This might help debugging some issues with unusual installations of API Proxy.
Previously the debug log looked like this:
> 2024-03-30 16:49:26.782 DEBUG (MainThread) [custom_components.tesla_custom] <ssl.SSLContext object at 0xffffaa55c4d0>
Now it looks like this:
> 2024-03-30 11:14:42.786 DEBUG (MainThread) [custom_components.tesla_custom] Trusting CA: {'subject': ((('commonName', 'c03d64a7-tesla-http-proxy'),),), 'issuer': ((('commonName', 'c03d64a7-tesla-http-proxy'),),), 'version': 3, 'serialNumber': '2431556855DA35772206E0D7305F10AA31A4119A', 'notBefore': 'Mar 24 01:43:47 2024 GMT', 'notAfter': 'Mar 22 01:43:47 2034 GMT'}

docs: improve logging for SSL_CONTEXT

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/issue_car.yml
.github/ISSUE_TEMPLATE/issue_powerwall.yml

Tweaks to make the issue templates nicer to use
- Fix link to Fleet API in `car` issue template
- Remove default titles, as this meant titles might not be set correctly & labels already describe if it's `car`, `powerwall`, etc
- Add `enhancement` label for `feature` issue

chore: Tidy up issue templates

---

custom_components/tesla_custom/sensor.py

Exposes the polling interval as a sensor as requested in #946

feat: Expose polling interval as a sensor

---

custom_components/tesla_custom/sensor.py

* feat: Expose polling interval as a sensor
* style: auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
* feat: Expose polling interval as a sensor
* style: auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
---------

feat: Expose polling interval as a sensor (#948)

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/base.py

https://github.com/alandtse/tesla/pull/953 didn't work because the data is actually a `bool`.  This is a second attempt
#948 made me realize that the car data was being polled far less frequently than I thought as the underlying library was caching, but every time the coordinator fired, it would still callback all the listeners and write the state of all the entities which meant we ended up writing state every 10 seconds even if nothing has changed.
Keep track of when the controller was last updated in each entity and if it has not changed, we skip the state write.
This reduced the number of calls to `async_write_ha_state` by 62% on my production HA instance!

perf: avoid writing state when the controller did not actually update

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/base.py

* perf: avoid writing state when the controller did not actually update
#948 made me realize that the car data was being polled far less frequently than I thought as the underlying library was caching, but every time the coordinator fired, it would still callback all the listeners and write the state of all the entities which meant we ended up writing state every 10 seconds even if nothing has changed.
Keep track of when the controller was last updated in each entity and if it has not changed, we skip the state write.
This reduced the number of calls to `async_write_ha_state` by 62% on my production HA instance!
* fix async_added_to_hass was being overridden and forgot to remove in pr

perf: only write state when data changes (#954)

---

custom_components/tesla_custom/__init__.py
custom_components/tesla_custom/base.py
custom_components/tesla_custom/teslamate.py

Note that I don't use mqtt so I don't have a way to test this.  I was only able to test that it didn't regress the incoming data from the coordinator polling.
fixes #986

fix: update coordinator update time when receiving data from mqtt

---

custom_components/tesla_custom/__init__.py

Nothing was being awaited in _debounced so it could be a normal function decorated with `@callback` to run in the event loop and did not need to be a coro. This avoids creating a task when the async_call_later fires
Note as with #989, I don't use mqtt/teslamate so I have no real world test case for this

perf: avoid creating a task for debounced listener update

---

custom_components/tesla_custom/climate.py
custom_components/tesla_custom/icons.json
custom_components/tesla_custom/strings.json
custom_components/tesla_custom/translations/en.json
tests/test_climate.py

Added icons for climate preset modes and fan modes
***Breaking Changes***
strings.json and icons.json must be used for adding icons to climate preset and fan modes. Translation keys in these files can only consist of lowercase letters, numbers, and underscore.
1. Preset modes has to be renamed to ["normal", "defrost", "keep", "dog", "camp"], and 
2. Fan modes has to be renamed to ["off", "bioweapon"].
Please update your scripts and automations after this update.
Fixes issue [725](https://github.com/alandtse/tesla/issues/725)

feat: add climate preset icons

---

custom_components/tesla_custom/__init__.py

load_verify_locations should run in the executor
related issue https://github.com/alandtse/tesla/issues/1029

fix: fix api proxy cert blocking the event loop

---

README.md

as discussed in #1048
* linked to the super helpful wiki page that tells you how to do a full setup with DuckDNS etc.
* note that the wiki already links to the `tesla_http_proxy/DOCS.md` file so I think it's OK to replace that link.
* added a few cross-links for easier navigation
* mentioned `teslajsonpy.exceptions.TeslaException` for SEO / discoverability

docs: streamline docs for Fleet API setup

---

custom_components/tesla_custom/base.py

Partial fix to #1059 
This pull request recognises an empty string for `display_name` during setup.

fix: append model when name is empty

---

custom_components/tesla_custom/services.py

path_vars is not required for every action api call and is not enforced to be required. But when not provided it results in an uncaught exception.
This fix just ensures that if path_vars is not provided no exception occurs by providing as default an empty dictionary,

fix: Uncaught exception when path_vars is not provided in action API
